/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as MainIndexRouteImport } from './routes/main/index'
import { Route as ExamplesPokemonRouteRouteImport } from './routes/examples/pokemon/route'
import { Route as MainTestIndexRouteImport } from './routes/main/test/index'
import { Route as ExamplesPokemonIndexRouteImport } from './routes/examples/pokemon/index'
import { Route as ExamplesPokemonIdIndexRouteImport } from './routes/examples/pokemon/$id/index'
import { Route as MainTestExamsSubmitIndexRouteImport } from './routes/main/test/exams/submit/index'
import { Route as MainTestExamsSubmitActiveIndexRouteImport } from './routes/main/test/exams/submit/active/index'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ExamplesPokemonRouteRoute = ExamplesPokemonRouteRouteImport.update({
  id: '/examples/pokemon',
  path: '/examples/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTestIndexRoute = MainTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ExamplesPokemonIndexRoute = ExamplesPokemonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesPokemonRouteRoute,
} as any)
const ExamplesPokemonIdIndexRoute = ExamplesPokemonIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ExamplesPokemonRouteRoute,
} as any)
const MainTestExamsSubmitIndexRoute =
  MainTestExamsSubmitIndexRouteImport.update({
    id: '/test/exams/submit/',
    path: '/test/exams/submit/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainTestExamsSubmitActiveIndexRoute =
  MainTestExamsSubmitActiveIndexRouteImport.update({
    id: '/test/exams/submit/active/',
    path: '/test/exams/submit/active/',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRouteRouteWithChildren
  '/examples/pokemon': typeof ExamplesPokemonRouteRouteWithChildren
  '/main/': typeof MainIndexRoute
  '/signup': typeof SignupIndexRoute
  '/examples/pokemon/': typeof ExamplesPokemonIndexRoute
  '/main/test': typeof MainTestIndexRoute
  '/examples/pokemon/$id': typeof ExamplesPokemonIdIndexRoute
  '/main/test/exams/submit': typeof MainTestExamsSubmitIndexRoute
  '/main/test/exams/submit/active': typeof MainTestExamsSubmitActiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainIndexRoute
  '/signup': typeof SignupIndexRoute
  '/examples/pokemon': typeof ExamplesPokemonIndexRoute
  '/main/test': typeof MainTestIndexRoute
  '/examples/pokemon/$id': typeof ExamplesPokemonIdIndexRoute
  '/main/test/exams/submit': typeof MainTestExamsSubmitIndexRoute
  '/main/test/exams/submit/active': typeof MainTestExamsSubmitActiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRouteRouteWithChildren
  '/examples/pokemon': typeof ExamplesPokemonRouteRouteWithChildren
  '/main/': typeof MainIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/examples/pokemon/': typeof ExamplesPokemonIndexRoute
  '/main/test/': typeof MainTestIndexRoute
  '/examples/pokemon/$id/': typeof ExamplesPokemonIdIndexRoute
  '/main/test/exams/submit/': typeof MainTestExamsSubmitIndexRoute
  '/main/test/exams/submit/active/': typeof MainTestExamsSubmitActiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/examples/pokemon'
    | '/main/'
    | '/signup'
    | '/examples/pokemon/'
    | '/main/test'
    | '/examples/pokemon/$id'
    | '/main/test/exams/submit'
    | '/main/test/exams/submit/active'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/signup'
    | '/examples/pokemon'
    | '/main/test'
    | '/examples/pokemon/$id'
    | '/main/test/exams/submit'
    | '/main/test/exams/submit/active'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/examples/pokemon'
    | '/main/'
    | '/signup/'
    | '/examples/pokemon/'
    | '/main/test/'
    | '/examples/pokemon/$id/'
    | '/main/test/exams/submit/'
    | '/main/test/exams/submit/active/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ExamplesPokemonRouteRoute: typeof ExamplesPokemonRouteRouteWithChildren
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/examples/pokemon': {
      id: '/examples/pokemon'
      path: '/examples/pokemon'
      fullPath: '/examples/pokemon'
      preLoaderRoute: typeof ExamplesPokemonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/test/': {
      id: '/main/test/'
      path: '/test'
      fullPath: '/main/test'
      preLoaderRoute: typeof MainTestIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/examples/pokemon/': {
      id: '/examples/pokemon/'
      path: '/'
      fullPath: '/examples/pokemon/'
      preLoaderRoute: typeof ExamplesPokemonIndexRouteImport
      parentRoute: typeof ExamplesPokemonRouteRoute
    }
    '/examples/pokemon/$id/': {
      id: '/examples/pokemon/$id/'
      path: '/$id'
      fullPath: '/examples/pokemon/$id'
      preLoaderRoute: typeof ExamplesPokemonIdIndexRouteImport
      parentRoute: typeof ExamplesPokemonRouteRoute
    }
    '/main/test/exams/submit/': {
      id: '/main/test/exams/submit/'
      path: '/test/exams/submit'
      fullPath: '/main/test/exams/submit'
      preLoaderRoute: typeof MainTestExamsSubmitIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/main/test/exams/submit/active/': {
      id: '/main/test/exams/submit/active/'
      path: '/test/exams/submit/active'
      fullPath: '/main/test/exams/submit/active'
      preLoaderRoute: typeof MainTestExamsSubmitActiveIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainTestIndexRoute: typeof MainTestIndexRoute
  MainTestExamsSubmitIndexRoute: typeof MainTestExamsSubmitIndexRoute
  MainTestExamsSubmitActiveIndexRoute: typeof MainTestExamsSubmitActiveIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainTestIndexRoute: MainTestIndexRoute,
  MainTestExamsSubmitIndexRoute: MainTestExamsSubmitIndexRoute,
  MainTestExamsSubmitActiveIndexRoute: MainTestExamsSubmitActiveIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface ExamplesPokemonRouteRouteChildren {
  ExamplesPokemonIndexRoute: typeof ExamplesPokemonIndexRoute
  ExamplesPokemonIdIndexRoute: typeof ExamplesPokemonIdIndexRoute
}

const ExamplesPokemonRouteRouteChildren: ExamplesPokemonRouteRouteChildren = {
  ExamplesPokemonIndexRoute: ExamplesPokemonIndexRoute,
  ExamplesPokemonIdIndexRoute: ExamplesPokemonIdIndexRoute,
}

const ExamplesPokemonRouteRouteWithChildren =
  ExamplesPokemonRouteRoute._addFileChildren(ExamplesPokemonRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  ExamplesPokemonRouteRoute: ExamplesPokemonRouteRouteWithChildren,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
